# command: bundle exec foreman start
version: '2'
services:
  app:
    build: .
    command: bundle exec foreman start
    volumes:
      - ./:/app
    volumes_from:
      - box
    env_file:
      - ./.docker/db.env
    ports:
      - '3000:3000'
      - '5000:5000'
    links:
      - db

  db:
    # restart: always
    image: sameersbn/postgresql
    ports:
      - 5432
    env_file:
      - ./.docker/db.env
    volumes:
      - db_data:/var/lib/postgresql

  box:
    image: busybox
    volumes:
      - box:/box

volumes:
  box:
  db_data:
