---
:welcome_message: 'Type /start to create a new company'
:finish_message: 'Спасибо, ваш проект добавлен к нам в базу и после проверки будет отправлен инвесторам'
:unknown_command: 'Unknown command. Type /start to create a new company'
:questions:
- :id: company_name
  :text: "Напишите название вашего проекта"
  :next_question_id: q2

- :id: q2
  :text: "В какой стране вы хотите запустить свой проект?"
  :options:
    - "111"
    - "2222"
    - "333"
    - "3444"
    - "5555"
    - "6666"
    - "7777"
  :next_question_id: q3

- :id: q3
  :text: "Расскажите поподробнее о вашем потенциальном покупателе:\nКаков возраст вашего потенциального покупателя?"
  :options:
    - до 18
    - 19-25
    - 26-35
    - 36-45
    - 45+
  :next_question_id: q4

- :id: q4
  :text: "Мужчины или женщины преобладают среди ваших клиентов?"
  :next_question_id: q5
  :options:
    - Мужчины
    - Женщины
    - Приблизительно поровну

- :id: q5
  :text: "Какой средний ежемесячный доход вашего покупателя?"
  :next_question_id: q6
  :options:
    - до 30 000 рублей
    - От 30 до 50 тыс
    - от 50 до 100 тыс
    - Больше 100 тыс.

- :id: q6
  :text: "Давайте поговорим о ваших конкурентах, знаете ли вы их? Расскажите кратко о ваших конкурентах, добавь несколько ссылок в ваше описание"
  :next_question_id: q7

- :id: q7
  :text: "
    В каком сегменте вы делаете продукт?:\n

    1. Life Science\n
    - BioTech\n
    - HealthTech\n
    - FoodTech\n
    - Biology\n
    - Anatomy\n
    - Anthropology\n
    - Astrobiology\n
    - Biochemistry\n
    - Biogeography\n
    - Biological engineering\n
    - Biophysics\n
    - Behavioral neuroscience\n
    - Botany\n
    - Developmental biology\n
    - Ecology\n
    - Physiology\n
    - Sociobiology\n
    - Systematics\n
    - Zoology\n

    2. ICT\n
    - SaaS\n
    - Big Data\n
    - FinTech & Cyber-Security\n
    - Cloud Computing\n
    - Blockchain\n

    3. IoT\n
    - Sensors\n
    - Wearables\n
    - Smart Grid\n
    - Smart Houses\n
    - HardWare\n
    - Media\n
    - Environmental monitoring\n
    - Infrastructure management\n
    - Manufacturing\n
    - Energy management\n
    - Medical and healthcare systems\n
    - Building and home automation\n
    - Transportation\n
    - Large scale deployments\n
    - Consumer application\n

    4. Robotics\n
    - Drones\n
    - Other\n

    5. Artificial Intelligence & Virtual Reality\n
    - Content\n
    - Services\n
    - NeuroTech\n
    - GameDev\n

    6. E-Commerce\n
    - NeuroMarketing\n
    - Online goods and services\n
    - Retail services\n
    - Marketplace services\n
    - Mobile commerce\n
    - Customer service\n
    - E-procurement\n
    - Purchase-to-pay\n"
  :next_question_id: q8

- :id: q8
  :text: "Какое решение вы выберите для реализации вашего продукта?"
  :next_question_id: q9
  :options:
    - IT
    - IoT
    - Mobile
    - HardWare
    - eLearning
    - Applicatione
    - Commerce
    - AR/VR
    - Cloud

- :id: q9
  :text: "Как вы будете доносить информацию о проекте до вашей аудитории? (выберите 3 варианта)"
  :next_question_id: q10
  :options:
    - Контекстная реклама
    - SEM
    - SMM
    - Оффлайн
    - Ручные продажи
    - Выставки
    - Конференции
    - Через ЛПР вендора
    - Product Placement
    - Трендсеттеры

- :id: q10
  :text: "Поговорим о команде, сколько сейчас в ней человек?"
  :next_question_id: q11
  :options:
    - до 3х
    - до 5
    - до 10
    - до 20
    - больше 20

- :id: q11
  :text: "Напишите имена коллег, которые занимаются custdev ИЛИ дайте ссылки на их профили Linkedin(fb)"
  :next_question_id: q12

- :id: q12
  :text: "Сколько человек из команды занимаются Customer development? Расскажите об этих людях, добавьте ссылки на linkedIn или facebook"
  :next_question_id: q13

- :id: q13
  :text: "Сколько человек из команды занимаются Product development? Расскажите об этих людях, добавьте ссылки на linkedIn или facebook"
  :next_question_id: q14

- :id: q14
  :text: "У вас есть ментор в команде?"
  :next_question_id: q15
  :options:
    - да
    - нет

- :id: q15
  :text: "Как зовут этого человека? расскажите о его опыте, добавьте ссылки на linkedIn или facebook"
  :next_question_id: q16

- :id: q16
  :text: "У тебя есть готовая финансовая модель? Которую не стыдно показать инвестору"
  :next_question_id: q17
  :options:
    - да
    - нет

- :id: q17
  :text: "Прикрепи ссылку на свою финансовую модель"
  :next_question_id: q18

- :id: q18
  :text: "Далее будет серия из 3х вопросов ваши расходы. Вопрос 1. Какую часть бюджета ты будешь тратить на разработку продукта (найм разработчиков)?"
  :next_question_id: q19
  :options:
    - до 30%
    - 30-50%
    - больше 50

- :id: q19
  :text: "Вопрос 2. Какую часть бюджета ты будешь тратить на маркетинг(привлечение клиентов)?"
  :next_question_id: q20
  :options:
    - до 30%
    - 30-50%
    - больше 50

- :id: q20
  :text: "Вопрос 3. Какую часть бюджета ты будешь тратить на дополнительные (непредвиденные расходы)?"
  :next_question_id: q21
  :options:
    - до 30%
    - 30-50%
    - больше 50

- :id: q21
  :text: "Как вы собираетесь зарабатывать. Какие будут основные источники дохода?"
  :next_question_id: q22
  :options:
    - Модель по подписки
    - Комиссия с продаж
    - Продажа рекламы
    - Прямые продажи услуги (товара)

- :id: q22
  :text: "Опишите в чём преимущества вашего продукта? что у вас есть такого, что позволяет вам конкурировать на рынке"
  :next_question_id: q23

- :id: q23
  :text: "Теперь расскажите в чём ваше уникальное торговое предложение (УТП), что вы делаете?"
  :next_question_id: q24

- :id: q24
  :text: "Просчитана ли у вас юнит-экономика?"
  :next_question_id: q25
  :options:
    - да
    - нет

- :id: q25
  :text: "Сколько будет стоить привлечение 1 пользователя?"
  :next_question_id: q26

- :id: q26
  :text: "Какую конверсию вы ожидаете из пользователя в клиента, в процентном соотношении?"
  :next_question_id: q27

- :id: q27
  :text: "Какой средний чек?"
  :next_question_id: q28

- :id: q28
  :text: "Себестоимость продукта от среднего чека, в процентном соотношении?"
  :next_question_id: q29

- :id: q29
  :text: "Сколько раз пользователь вернётся и купит у вас ваш продукт? (удержание)"
  :next_question_id: q30

- :id: q30
  :text: "Сколько пользователей ты собираешься привлечь за 2 года?"
  :next_question_id: q31

- :id: q31
  :text: "Сколько ты собираешься потратить на рекламу за 2 года?"
  :next_question_id: q32

- :id: q32
  :text: "Какие будут фиксированные будет за 2 года?"
  :next_question_id: q33

- :id: q33
  :text: "Поздравляем! вы справились со всеми вопросами, осталось указать ваши контакные данные, чтобы заинетерсованные инвесторы могли с вами связать\nКак вас зовут? Укажите пожалуйста имя и фамилию"
  :next_question_id: q34

- :id: q34
  :text: "Ваш контактный емейл"
  :next_question_id: q35

- :id: q35
  :text: "И мобильный телефон"
  :next_question_id: q36

- :id: q36
  :text: "Что вы хотите от инвестора? (Например: ищу 100 000$ инвестиций за 10% акций компании)"
